### ISSUE TITLE
Not able to see and TLS packet 

### ISSUE THREAD

**Issue by minensh1291** [enthusiasticgeek/gstreamer-rtsp-ssl-example#1]
![Not_tls](https://user-images.githubusercontent.com/36298956/59766997-09a92680-92bf-11e9-97c2-58e45ed09806.png)

Hi ,
I have install gstreamer library and run server client example, Its working fine  but in wireshark  not  found any tls packet,  and  sgtraming data is sending as udp packet.

**Comment by enthusiasticgeek** [comment]
https://osqa-ask.wireshark.org/questions/42762/how-to-recognize-if-this-is-rtp-or-srtp-packet
https://flashphoner.com/docs/wcs5/wcs_docs/html/en/wcs-admin-guide/index.html?troubleshooting-network_traffic_analysis-webrtc-srtp.htm

Based on above both rtp and srtp should show as udp initially as protocol to decode needs to be specified. See above links. Try it and let me know what you find.

**Comment by enthusiasticgeek** [comment]
![SRTP](https://user-images.githubusercontent.com/4500752/73141050-a437c800-404d-11ea-9bb9-3af5edb37ce3.png)
![SRTP2](https://user-images.githubusercontent.com/4500752/73141051-a7cb4f00-404d-11ea-9c55-5a46d2612a25.png)

My wireshark shows the above data. From the above URL

"SRTP-traffic is encrypted. It means, that if somebody will try to playback it, then noise will be heard only instead of normal voice/ video. But only payload is encrypted. Main RTP-headers are not encrypted and they can be found in RTP-packet. It is convenient for SRTP-traffic characteristics analysis. In the example below SRTP-packet with Payload Type, Sequence Number, Timestamp, SSRC is shown.

As was described early, SRTP-packet headers are not encrypted, so SRTP-stream is fully available for quality, loss, jitter and delays analysis, as usual RTP-stream."
